### ISSUE TITLE
Query Related to APB protocol

### ISSUE THREAD

**Issue by shubhi704** [adnanashraf17501/uvm_APB-AMBA-3#1]
Hi, I've seen your code of APB protocol, can you please tell me why did you insert the wait state in the protocol? As it is not given in the APB specification.
And according to your design code, you had inserted the SEL in the input port where as in your presentation it is at the output port (which is correct). so can you please help me by answering these questions? 
I would be very grateful to you. 
Thank you

**Comment by adnanashraf17501** [comment]
> Hi, I've seen your code of APB protocol, can you please tell me why did you insert the wait state in the protocol? As it is not given in the APB specification.
> And according to your design code, you had inserted the SEL in the input port where as in your presentation it is at the output port (which is correct). so can you please help me by answering these questions?
> I would be very grateful to you.
> Thank you

Nice awareness...
Firstly we are setting up a test environment in specification we are given the signals input output and there operations but we in verification want to try some test cases like what will happen to the data if i try wait state and what will happen to data if i try without wait , we call them as test cases which are part of verification . If these tests pass then our verification is fine and we dont need to implement further using functional coverage we can check the correctness of our test case .

**Comment by adnanashraf17501** [comment]
Next one .... 
sel here is input for slave. But for master it is output . In interface unit you can verify the direction of connections where modport has been declared you will there modport for slave and master which will help. 

Thanks hope this will be helpful

**Comment by shubhi704** [comment]
Hi, Thank you for your response. 
Yes, your response is helpful.
Have a good day!

**Comment by adnanashraf17501** [comment]
You can close the issue for now ... 
Thanks
